name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile the code
      run: g++ simulator.cpp -o bgp_sim -std=c++17 -Wall

    - name: (Optional) Run the executable to test
      run: ./bgp_sim -c topology.conf
